### ISSUE TITLE
after installed tern_for_vim, exuberant ctags, jsctags, no tags are shown for js file when :TagbarToggle

### ISSUE THREAD

**Issue by hatelove85911** [preservim/tagbar#260]
I have installed tern_for_vim, exuberant ctags, jsctags and tagbar, I've put the bin of ctags and jsctags in path, I'm not sure if there's anything else I need to do. I tried opening a js file and toggle tagbar, no tags are shown:
![tagbar_toggle](https://cloud.githubusercontent.com/assets/2359121/6934033/1bd44d84-d861-11e4-9d54-67aeff0e68ad.png)

**Comment by AshlynnInWonderland** [comment]
I'm probably just an idiot and missing something, but this is happening for me too. The instructions for using jsctags aren't very in-depth and I'm not at all sure what to do with it after installation or if I should need to do anything.

**Comment by majutsushi** [comment]
Do you see any error messages if you run the `:messages` command? If not then try generating a debug log as explained in `:h tagbar-issues`. Also, which jstags are you using, https://github.com/ramitos/jsctags ?

**Comment by hatelove85911** [comment]
@majutsushi  
I'm using 
https://github.com/ramitos/jsctags

below is the :messages

```
Tagbar: Could not execute ctags for /cygdrive/c/Users/xxxx/vimtest.js!
Executed command: "'jsctags'  -f -  '/tmp/vpVEuaY/7.js'"
Command output:
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'C:\tmp\vpVEuaY\7.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.<anonymous> (C:\Users\I056958\AppData\Roaming\npm\node_modules\jsctags\bin\jsctags:44:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
(flags), mode);
```

**Comment by majutsushi** [comment]
Ugh, cygwin. It's always causing problems. Apparently you're using Vim from
cygwin, but a non-cygwin jsctags build, and jsctags can't handle the cygwin
paths that Vim passes to it. I'm not really sure what the right solution here
is, other than using both programs in either the cygwin or non-cygwin variant.

Technically there is a way to convert the different paths to each other, but I
can't think of a reliable way to detect whether that is necessary, because if
the conversion is done when it's not necessary then this could create the
reverse problem. So there would need to be a way to check whether the external
program is a cygwin program or not.

**Comment by hatelove85911** [comment]
@majutsushi 

Is following code enough for checking whether it's cygwin?
```
if has("win32unix")
    " Do something only in Cygwin
endif
```

**Comment by majutsushi** [comment]
Unfortunately not; that only tests whether Vim is the cygwin version, but for
proper cooperation Tagbar needs to know whether both Vim *and* ctags/jsctags
are cygwin or not.

So the current workaround would be that either both should be cygwin versions
or both should be non-cygwin versions. I would love to make other combinations
work too, but until there's a reliable way to determine the exact combination
in use I'm not sure how to proceed.

**Comment by benjah1** [comment]
Found a workaround, by create a symlinks in Windows. Open CMD, run

```
mklink /j c:\tmp c:\cygwin64\tmp
``` 

http://lifehacker.com/5496652/how-to-use-symlinks-in-windows

**Comment by maple-leaf** [comment]
Have issue here on mac. 
Some details here:
1, `tags` file is being generated correct
2, I can use `ctrl+]` and `ctrl+T` to jump tag.
3, call `:Tagbar` will get an window has `"No tags found"`
4, I delete `tags` file and try `ctrl+]` will raise `tag file not found` error, which is exptected.
5, It's same wheather I add  `let g:tagbar_ctags_bin='jsctags'` manually or not.
6, The js code is `AMD` way

And here's my `:TagbarDebug` output:

    1970-01-18 15:10:36.203723: AutoUpdate called [/the/path/to/project/root/]
    1970-01-18 15:10:36.204332: Vim filetype: '', sanitized filetype: ''
    1970-01-18 15:10:36.204465: Checking if file is valid [/the/path/to/project/root/]
    1970-01-18 15:10:36.204640: Empty filename or type
    1970-01-18 15:10:36.204796: Not a valid file, stopping processing
    1970-01-18 15:10:36.229692: AutoUpdate called [term://.//6907:git ls-files |"/Users/maple-leaf/.fzf/bin/fzf" -m --prompt "GitFiles> " --expect=ctrl-v,ctrl-x,ctrl-t > /var/folders/g7/tmk5tm096kb6gdjrtpj3w11h0000gn/T/nvimygqEaR/1;#FZF]
    1970-01-18 15:10:36.230325: Vim filetype: 'fzf', sanitized filetype: 'fzf'
    1970-01-18 15:10:36.230662: Checking if file is valid [term://.//6907:git ls-files |"/Users/maple-leaf/.fzf/bin/fzf" -m --prompt "GitFiles> " --expect=ctrl-v,ctrl-x,ctrl-t > /var/folders/g7/tmk5tm096kb6gdjrtpj3w11h0000gn/T/nvimygqEaR/1;#FZF]
    1970-01-18 15:10:36.231191: File not readable
    1970-01-18 15:10:36.231431: Not a valid file, stopping processing
    1970-01-18 15:10:37.530899: AutoUpdate called [/the/path/to/project/root/]
    1970-01-18 15:10:37.531163: Vim filetype: '', sanitized filetype: ''
    1970-01-18 15:10:37.531288: Checking if file is valid [/the/path/to/project/root/]
    1970-01-18 15:10:37.531415: Empty filename or type
    1970-01-18 15:10:37.531581: Not a valid file, stopping processing
    1970-01-18 15:10:38.420497: AutoUpdate called [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:38.420722: Vim filetype: 'javascript', sanitized filetype: 'javascript'
    1970-01-18 15:10:38.420852: Checking if file is valid [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:38.421121: New file, processing [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:38.421258: ProcessFile called [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:38.421398: Checking if file is valid [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:38.421773: typeinfo for file to process: {'ctagstype': 'javascript', 'ftype': 'javascript', 'kinddict': {'f': 1, 'v': 0}, 'ctagsargs': '-f -', 'sro': '.', 'getKind': function('39'), 'createKinddict': function('40'), 'kind2scope': {'f': 'namespace', 'v': 'namespace'}, 'ctagsbin': 'jsctags', 'scope2kind': {'namespace': 'v'}, 'New': function('38'), 'kinds': [{'short': 'v', 'long': 'variables', 'fold': 0, 'stl': 0}, {'short': 'f', 'long': 'functions', 'fold': 0, 'stl': 1}]}
    1970-01-18 15:10:38.424603: ExecuteCtagsOnFile called [/var/folders/g7/tmk5tm096kb6gdjrtpj3w11h0000gn/T/nvimygqEaR/2.js]
    1970-01-18 15:10:38.424889: EscapeCtagsCmd called
    1970-01-18 15:10:38.425017: ctags_bin: jsctags
    1970-01-18 15:10:38.425158: ctags_args (is a string):  -f - 
    1970-01-18 15:10:38.425514: Escaped ctags command: 'jsctags'  -f -  '/var/folders/g7/tmk5tm096kb6gdjrtpj3w11h0000gn/T/nvimygqEaR/2.js'
    1970-01-18 15:10:38.425684: Executing ctags command: 'jsctags'  -f -  '/var/folders/g7/tmk5tm096kb6gdjrtpj3w11h0000gn/T/nvimygqEaR/2.js'
    1970-01-18 15:10:39.181833: "js_v5/material/show.js" 714L, 28949C
    1970-01-18 15:10:39.344641: Ctags executed successfully
    1970-01-18 15:10:39.345194: Filetype tag kinds: ['f', 'v']
    1970-01-18 15:10:39.345398: Parsing ctags output
    1970-01-18 15:10:39.345611: Processing scoped tags
    1970-01-18 15:10:39.346204: Number of top-level tags: 0
    1970-01-18 15:10:39.346429: Processing kind: v, number of tags: 0
    1970-01-18 15:10:39.346863: Processing kind: f, number of tags: 0
    1970-01-18 15:10:39.347346: Setting current file [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:39.347866: AutoUpdate finished successfully
    1970-01-18 15:10:39.355380: AutoUpdate called [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:39.355613: Vim filetype: 'javascript', sanitized filetype: 'javascript'
    1970-01-18 15:10:39.355730: Checking if file is valid [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:39.356162: File data seems up to date [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:39.356517: Setting current file [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:39.356820: AutoUpdate finished successfully
    1970-01-18 15:10:39.372884: AutoUpdate called [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:39.373248: Vim filetype: 'javascript', sanitized filetype: 'javascript'
    1970-01-18 15:10:39.373418: Checking if file is valid [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:39.373757: File data seems up to date [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:39.374027: Setting current file [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:39.374502: AutoUpdate finished successfully
    1970-01-18 15:10:43.752755: AutoUpdate called [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:43.753279: Vim filetype: 'javascript', sanitized filetype: 'javascript'
    1970-01-18 15:10:43.753463: Checking if file is valid [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:43.753773: File data seems up to date [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:43.754126: Setting current file [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:10:43.754541: AutoUpdate finished successfully
    1970-01-18 15:11:39.376006: ToggleWindow called
    1970-01-18 15:11:39.384455: OpenWindow called with flags: ''
    1970-01-18 15:11:39.384968: goto_win(): wincmd p, 1
    1970-01-18 15:11:39.385224: goto_win(): wincmd p, 1
    1970-01-18 15:11:39.587705: AutoUpdate called [/the/path/to/project/root/__Tagbar__.1]
    1970-01-18 15:11:39.587952: Still opening window, stopping processing
    1970-01-18 15:11:39.602194: InitWindow called with autoclose: 0
    1970-01-18 15:11:39.610187: AutoUpdate called [/the/path/to/project/root/__Tagbar__.1]
    1970-01-18 15:11:39.610451: In Tagbar window, stopping processing
    1970-01-18 15:11:39.614171: Mapping keys
    1970-01-18 15:11:39.615416: InitWindow finished
    1970-01-18 15:11:39.615578: AutoUpdate called [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:11:39.615749: Vim filetype: 'javascript', sanitized filetype: 'javascript'
    1970-01-18 15:11:39.615951: Checking if file is valid [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:11:39.616340: File data seems up to date [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:11:39.616538: RenderContent called
    1970-01-18 15:11:39.616737: Redisplaying file [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:11:39.617106: No tags found, skipping printing.
    1970-01-18 15:11:39.617455: Setting current file [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:11:39.620210: AutoUpdate finished successfully
    1970-01-18 15:11:39.672376: goto_win(): 1wincmd w, 1
    1970-01-18 15:11:39.672685: goto_win(): 1wincmd w, 0
    1970-01-18 15:11:39.672832: OpenWindow finished
    1970-01-18 15:11:39.672952: ToggleWindow finished
    1970-01-18 15:11:43.772689: AutoUpdate called [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:11:43.773266: Vim filetype: 'javascript', sanitized filetype: 'javascript'
    1970-01-18 15:11:43.773478: Checking if file is valid [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:11:43.773897: File data seems up to date [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:11:43.774204: Setting current file [/the/path/to/project/root/js_v5/material/show.js]
    1970-01-18 15:11:43.774596: goto_win(): wincmd p, 1
    1970-01-18 15:11:43.774811: goto_win(): 2wincmd w, 1
    1970-01-18 15:11:43.778411: goto_win(): 2wincmd w, 1
    1970-01-18 15:11:43.778578: goto_win(): 1wincmd w, 1
    1970-01-18 15:11:43.778761: AutoUpdate finished successfully

**Comment by majutsushi** [comment]
@maple-leaf That seems to be a very different issue. The current issue is about cygwin, and since you're on a mac that doesn't apply.

Also you're talking about a `tags` file, but Tagbar doesn't use any tag files. It does everything in-memory.

Please open a new issue and mention
- what jsctags you're using, and the version of it,
- how the `tags` file was generated (since you seem to be saying that it is correct),
- and what the output of `jsctags -f - show.js` is.

**Comment by alswl** [comment]
My error message is
```
Executed command: "'/home/alswl/local/bin/markdown2ctags.py'  -f - --sort=yes  '/tmp/vdU7Jgt/1317.md'"
Command output:
Traceback (most recent call last):
  File "/home/alswl/local/bin/markdown2ctags.py", line 236, in <module>
    main()
  File "/home/alswl/local/bin/markdown2ctags.py", line 227, in main
    sections = findSections(filename, lines)
  File "/home/alswl/local/bin/markdown2ctags.py", line 122, in findSections
    if line.startswith("```"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
Exit code: 1 
```

I find the Python version of `markdown2ctags.py` required Python2, but my linux default Python version is 3, so edit this file.

```
#!/usr/bin/env python
```

to

```
#!/usr/bin/env python2
```

And this plugin works.

**Comment by raven42** [comment]
@hatelove85911 Are you able to provide a workaround for this issue? We are looking to close out any older issues if the issue had a valid solution or workaround available.

**Comment by alerque** [comment]
Also note almost everything I see in this issue is outdated. Exuberant CTAGS is on the verge of complete deprecation, `jctags` is no longer our preferred way to handle JS (Universal CTAGS handles it well), and the the Python 2 version of `markdown2ctags.py` is EOL'ed, there are better ways to generate tags for Markdown now. Unless somebody confirms an active issue here not related to those deprecated things I think this issue probably really is stale.

**Comment by raven42** [comment]
Closing this out as there has been no response from anyone as to the reproducibility of this issue. Please reopen if this is still an issue.
